fix(ubuntu): Adding custom INIT INFO for Ubuntu
Fix the error
"update-rc.d: error: ... Default-Start contains no runlevels"
on Ubuntu execution due to configuration of chk only

diff --git a/templates/service.j2 b/templates/service.j2
--- a/templates/service.j2
+++ b/templates/service.j2
@@ -1,74 +1,82 @@
 #!/bin/bash
+{% if ansible_distribution == "Ubuntu" %}
+### BEGIN INIT INFO
+# Provides:          {{ item.value.file_name }}
+# Required-Start:    $all
+# Default-Start:     2 3 4 5
+### END INIT INFO
+{% else %}
 # chkconfig: 2345 80 95
+{% endif %}
 
 SERVICE_NAME="{{ item.value.file_name }}"
-DAEMON="{{ item.value.daemon_start }}"
+DAEMON_START="{{ item.value.daemon_start }}"
 DAEMON_OPTS="{{ item.value.daemon_opts }}"
 DAEMON_STOP="{{ item.value.daemon_stop }}"
 
-if [ ! -x $DAEMON ]; then
-  echo "ERROR: Can't execute $DAEMON."
-  exit 1
+if [ ! -x $DAEMON_START ]; then
+	echo "ERROR: Can't execute $DAEMON_START."
+	exit 1
 fi
 
 start_service() {
-  echo -n " * Starting $SERVICE_NAME... "
-  {{ item.value.daemon_status }}
+	echo -n " * Starting $SERVICE_NAME... "
+	{{ item.value.daemon_status }}
 
-  if [ $? -eq 1 ]; then
-    $DAEMON $DAEMON_OPTS
-    if [ $? -eq 255 ]; then
-      echo "couldn't start :("
-      exit 1
-    fi
-  fi
+	if [ $? -eq 1 ]; then
+		$DAEMON_START $DAEMON_OPTS
+		if [ $? -eq 255 ]; then
+			echo "couldn't start :("
+			exit 1
+		fi
+	fi
 
-  echo "done"
+	echo "done"
 }
 
 stop_service() {
-  echo -n " * Stopping $SERVICE_NAME... "
-  $DAEMON_STOP
-  if [ $? -eq 1 ]; then
-    echo "not running"
-    return
-  fi
+	echo -n " * Stopping $SERVICE_NAME... "
+	$DAEMON_STOP
+	if [ $? -eq 1 ]; then
+		echo "not running"
+		return
+	fi
 
-  echo "done"
+	echo "done"
 }
 
 status_service() {
-  echo -n "Checking $SERVICE_NAME..."
-  {{ item.value.daemon_status }}
-  if [ $? -eq 1 ]; then
-    echo "not running"
-    return
-  fi
+	echo -n "Checking $SERVICE_NAME..."
+	{{ item.value.daemon_status }}
+	if [ $? -eq 1 ]; then
+		echo "not running"
+		return
+	fi
 
-  echo "running"
+	echo "running"
 }
 
 case "$1" in
-  start)
-    start_service
-    exit 0
-    ;;
-  stop)
-    stop_service
-    exit 0
-    ;;
-  status)
-    status_service
-    ;;
-  restart)
-    stop_service
-    start_service
-    exit 0
-    ;;
-  *)
-    echo "Usage: service $SERVICE_NAME {start|stop|status|restart}" >&2
-    exit 1
-    ;;
+start)
+	start_service
+	exit 0
+	;;
+stop)
+	stop_service
+	exit 0
+	;;
+status)
+	status_service
+	;;
+restart)
+	stop_service
+	start_service
+	exit 0
+	;;
+*)
+	echo "Usage: service $SERVICE_NAME {start|stop|status|restart}" >&2
+	exit 1
+	;;
 esac
 
 exit 0
